# FullFace Gaze Estimation Model Configuration

# データ設定
data:
  labels_csv: "data/labels.csv"
  test_size: 0.2
  random_state: 42
  augment: false  # データ拡張は使用しない（論文・設計書に記載なし）

# モデル設定
model:
  input_shape: [224, 224, 3]
  kernel_size: 7
  dropout_rate: 0.1
  learning_rate: 0.0001  # 1e-4

# 学習設定
training:
  epochs: 100
  batch_size: 32
  early_stopping: true
  patience: 10
  save_dir: "models"

# 評価設定
evaluation:
  ppi: 96  # モニタのPPI
  distance_cm: 32.5  # 目とスクリーンの距離（cm）
